#!/usr/bin/env node
// Vendor Material Icon Theme file icons + associations into the app.
//
//   npm pack material-icon-theme && tar xzf material-icon-theme-*.tgz
//   node tools/gen_material_icons.mjs path/to/package
//
// Reads the package's official `dist/material-icons.json` (fileExtensions /
// fileNames / default `file`), overlays its `light` block (the app UI is light),
// copies only the referenced `icons/*.svg` into `assets/material/`, and writes
// `src/ui/file_icons_generated.rs`. Folder icons are intentionally ignored.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const pkg = process.argv[2];
if (!pkg) {
  console.error("usage: gen_material_icons.mjs <material-icon-theme package dir>");
  process.exit(1);
}
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const manifest = JSON.parse(fs.readFileSync(path.join(pkg, "dist/material-icons.json"), "utf8"));
const version = JSON.parse(fs.readFileSync(path.join(pkg, "package.json"), "utf8")).version;

// VS Code matches file names / extensions case-insensitively.
const overlay = (base, light) => {
  const out = new Map();
  for (const src of [base, light ?? {}]) {
    for (const [k, v] of Object.entries(src)) out.set(k.toLowerCase(), v);
  }
  return [...out.entries()].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
};
const extensions = overlay(manifest.fileExtensions, manifest.light?.fileExtensions);
const names = overlay(manifest.fileNames, manifest.light?.fileNames);
const fallback = manifest.file;

const used = new Set([fallback, ...extensions.map(([, v]) => v), ...names.map(([, v]) => v)]);
const outDir = path.join(root, "assets/material");
fs.rmSync(outDir, { recursive: true, force: true });
fs.mkdirSync(outDir, { recursive: true });
for (const icon of used) {
  const def = manifest.iconDefinitions[icon];
  if (!def) throw new Error(`no iconDefinition for ${icon}`);
  fs.copyFileSync(path.join(pkg, "dist", def.iconPath), path.join(outDir, `${icon}.svg`));
}

const q = JSON.stringify;
const table = (rows) => rows.map(([k, v]) => `    (${q(k)}, ${q(`material/${v}.svg`)}),`).join("\n");
const icons = [...used].sort((a, b) => {
  const [x, y] = [`material/${a}.svg`, `material/${b}.svg`];
  return x < y ? -1 : x > y ? 1 : 0;
});
const rs = `// @generated by tools/gen_material_icons.mjs from material-icon-theme ${version} (MIT).
// Do not edit; rerun the script. Keys are lowercase and sorted for binary search.

/// Default icon for files with no extension / name association.
pub(super) const DEFAULT_FILE_ICON: &str = ${q(`material/${fallback}.svg`)};

/// \`fileExtensions\`: extension (without leading dot, may contain dots) -> asset path.
pub(super) static FILE_EXTENSIONS: &[(&str, &str)] = &[
${table(extensions)}
];

/// \`fileNames\`: lowercase basename -> asset path.
pub(super) static FILE_NAMES: &[(&str, &str)] = &[
${table(names)}
];

/// Every embedded file icon, sorted by asset path.
pub(super) static MATERIAL_ICONS: &[(&str, &[u8])] = &[
${icons
  .map((i) => `    (${q(`material/${i}.svg`)}, include_bytes!(${q(`../../assets/material/${i}.svg`)})),`)
  .join("\n")}
];
`;
fs.writeFileSync(path.join(root, "src/ui/file_icons_generated.rs"), rs);
console.log(`${used.size} icons, ${extensions.length} extensions, ${names.length} names (v${version})`);
